name: Build Docker image

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Docker image name'
        required: true
        type: string
      tag:
        description: 'Docker image tag'
        required: true
        type: string
    outputs:
      image_name:
        description: 'The Docker image tag based on the commit SHA'
        value: ${{ jobs.build.outputs.image_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.build_image.outputs.image_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Validate inputs
        run: |
          if [ -z "${{ inputs.image_name }}" ]; then
            echo "Error: El nombre de la imagen Docker (image_name) no puede estar vacío."
            exit 1
          fi
          if [ -z "${{ inputs.tag }}" ]; then
            echo "Error: El tag de la imagen Docker (tag) no puede estar vacío."
            exit 1
          fi

      - name: Build Docker image
        id: build_image
        run: |
          docker build -t ${{ inputs.image_name }}:${{ inputs.tag }} . --file Dockerfile
          if [ $? -eq 0 ]; then
            echo "Construcción de la imagen correcta ${{ inputs.image_name }}"
          else
            echo "No se ha construido la imagen"
            exit 1
          fi
          echo "image_name=${{ inputs.image_name }}" >> $GITHUB_OUTPUT

      - name: List Docker images
        run: docker images

      - name: Save Docker image to file
        run: docker save -o image.tar ${{ inputs.image_name }}:${{ inputs.tag }}
        
      - name: Upload Docker image file
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

      