name: Set Docker image tag

on:
  workflow_call:
    outputs:
      tag:
        description: 'The Docker image tag based on the commit SHA'
        value: ${{ jobs.build.outputs.tag }}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Docker image tag
        id: set-tag
        run: |
          tag=$(echo ${GITHUB_SHA} | cut -c1-7)
          echo "tag=$tag" >> $GITHUB_OUTPUT
